[package]
name = "jpop-songs"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.11.1"
axum = { version = "0.4.5" }
reqwest = { version = "0.11.9", features = ["json"] }
scraper = "0.12.0"
serde = { version = "1.0.136", features = ["derive"]}
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["env-filter"] }

